[package]
name = "honkers-launcher"
version = "1.0.1"
description = "Honkers launcher"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = 3

[build-dependencies]
gtk4 = "0.4"

[dependencies]
gtk4 = "0.4"
libadwaita = "0.1"

anime-game-core = { path = "anime-game-core", features = ["all", "static", "honkai"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dirs = "4.0.0"
wait_not_await = "0.2.1"
regex = "1.6.0"
lazy_static = "1.4.0"
anyhow = "1.0"
